=== janlam-uio/survey-api-schemas/schema/FormMetadata.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "FormMetadata.json",
    "$comment": "$id should be URL where the schema is available.",
    "description": "Nettskjema form metadata",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "$schema",
        "permissions",
        "activatedOn",
        "activatedBy",
        "deactivatedOn",
        "deactivatedBy",
        "active",
        "questions"
    ],
    "properties": {
        "$schema": {
            "description": "Schema this form metadata conforms to.",
            "type": "string"
        },
        "datasets": {
            "description": "What datasets should be produced.",
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "csv",
                    "excel",
                    "spss"
                ],
                "uniqueItems": true
            }
        },
        "permissions": {
            "description": "Permissions settings for form.",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "datasets": {
                    "description": "Access control for dataloader outputs.",
                    "type": "string"
                },
                "api": {
                    "description": "Access control for API (inside of TSD).",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "activatedOn": {
            "description": "When the form was activated.",
            "type": "string",
            "format": "date-time"
        },
        "deactivatedOn": {
            "description": "When the form was deactivated.",
            "type": "string",
            "format": "date-time"
        },
        "activatedBy": {
            "description": "User who activated the form.",
            "type": "string"
        },
        "deactivatedBy": {
            "description": "User who deactivated the form.",
            "type": "string"
        },
        "active": {
            "description": "Is the form currently active.",
            "type": "boolean"
        },
        "isConsentForm": {
            "description": "Is this a consent form.",
            "type": "boolean"
        },
        "questions": {
            "description": "Metadata describing the questions in the nettskjema.",
            "type": "array",
            "items": {
                "$ref": "#/$defs/question"
            }
        }
    },
    "$defs": {
        "question": {
            "description": "A question in the nettskjema.",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "description": "Unique identifier for the question.",
                    "type": "number"
                },
                "text": {
                    "decription": "The actual question.",
                    "type": "string"
                },
                "questionType": {
                    "$ref": "QuestionType.json"
                },
                "codebookCode": {
                    "description": "The codebook code for this question.",
                    "type": "string"
                },
                "isIDQuestion": {
                    "description": "Is this question containing an ID",
                    "type": "string",
                    "enum": [
                        "no",
                        "national_id_number",
                        "feide_id",
                        "dataporten_sub"
                    ]
                },
                "isConsentQuestion": {
                    "description": "Is this a consent question.",
                    "type": "boolean"
                }
            }
        }
    }
}

=== janlam-uio/survey-api-schemas/schema/tests/form_valid_1.json
{
  "$schema": "../FormMetadata.json",
  "datasets": [
    "csv",
    "excel",
    "spss"
  ],
  "permissions": {
    "datasets": "pXX-member-group",
    "api": [
      "pXX-core-group",
      "pXX-admin-group"
    ]
  },
  "activatedOn": "timestamp",
  "activatedBy": "pxx-user",
  "deactivatedOn": "timestamp",
  "deactivatedBy": "pxx-user",
  "active": true,
  "isConsentForm": true,
  "questions": [
    {
      "id": 1111,
      "text": "What do you ..",
      "questionType": "checkBox",
      "codebookCode": "question_1",
      "isIDQuestion": "no",
      "isConsentQuestion": true
    }
  ]
}
